#!/bin/sh

check_updates() {
    (
        cd "$1"
        echo
        echo
        echo
        echo
        echo "Checking $1 ($(git branch --show-current))"
        git branch -a
        git fetch upstream 2>/dev/null && git merge --ff-only "upstream/$(git branch --show-current)" || true

        sleep 1
    )
}

for dir in *; do
    if test -e "$dir/.git"; then
        check_updates "$dir"
    fi
done
